import { Injectable } from '@angular/core';

export interface PhoneArea {
  text: string; 
  code: string; 
  country: string;
  flag: string;
}

@Injectable({
  providedIn: 'root'
})
export class PhoneServiceService {

  phoneVerification?: any
  phoneNumbers: PhoneArea[] = [
    { text: '🇺🇸 +1   United States', code: '+1', country: 'US', flag: '🇺🇸' },
    { text: '🇨🇦 +1   Canada', code: '+1', country: 'CA', flag: '🇨🇦' },
    { text: '🇷🇺 +7   Russia', code: '+7', country: 'RU', flag: '🇷🇺' },
    { text: '🇪🇬 +20  Egypt', code: '+20', country: 'EG', flag: '🇪🇬' },
    { text: '🇿🇦 +27  South Africa', code: '+27', country: 'ZA', flag: '🇿🇦' },
    { text: '🇬🇷 +30  Greece', code: '+30', country: 'GR', flag: '🇬🇷' },
    { text: '🇳🇱 +31  Netherlands', code: '+31', country: 'NL', flag: '🇳🇱' },
    { text: '🇧🇪 +32  Belgium', code: '+32', country: 'BE', flag: '🇧🇪' },
    { text: '🇫🇷 +33  France', code: '+33', country: 'FR', flag: '🇫🇷' },
    { text: '🇪🇸 +34  Spain', code: '+34', country: 'ES', flag: '🇪🇸' },
    { text: '🇭🇺 +36  Hungary', code: '+36', country: 'HU', flag: '🇭🇺' },
    { text: '🇮🇹 +39  Italy', code: '+39', country: 'IT', flag: '🇮🇹' },
    { text: '🇷🇴 +40  Romania', code: '+40', country: 'RO', flag: '🇷🇴' },
    { text: '🇨🇭 +41  Switzerland', code: '+41', country: 'CH', flag: '🇨🇭' },
    { text: '🇦🇹 +43  Austria', code: '+43', country: 'AT', flag: '🇦🇹' },
    { text: '🇬🇧 +44  United Kingdom', code: '+44', country: 'GB', flag: '🇬🇧' },
    { text: '🇩🇰 +45  Denmark', code: '+45', country: 'DK', flag: '🇩🇰' },
    { text: '🇸🇪 +46  Sweden', code: '+46', country: 'SE', flag: '🇸🇪' },
    { text: '🇳🇴 +47  Norway', code: '+47', country: 'NO', flag: '🇳🇴' },
    { text: '🇵🇱 +48  Poland', code: '+48', country: 'PL', flag: '🇵🇱' },
    { text: '🇩🇪 +49  Germany', code: '+49', country: 'DE', flag: '🇩🇪' },
    { text: '🇵🇪 +51  Peru', code: '+51', country: 'PE', flag: '🇵🇪' },
    { text: '🇲🇽 +52  Mexico', code: '+52', country: 'MX', flag: '🇲🇽' },
    { text: '🇨🇺 +53  Cuba', code: '+53', country: 'CU', flag: '🇨🇺' },
    { text: '🇦🇷 +54  Argentina', code: '+54', country: 'AR', flag: '🇦🇷' },
    { text: '🇧🇷 +55  Brazil', code: '+55', country: 'BR', flag: '🇧🇷' },
    { text: '🇨🇱 +56  Chile', code: '+56', country: 'CL', flag: '🇨🇱' },
    { text: '🇨🇴 +57  Colombia', code: '+57', country: 'CO', flag: '🇨🇴' },
    { text: '🇻🇪 +58  Venezuela', code: '+58', country: 'VE', flag: '🇻🇪' },
    { text: '🇲🇾 +60  Malaysia', code: '+60', country: 'MY', flag: '🇲🇾' },
    { text: '🇦🇺 +61  Australia', code: '+61', country: 'AU', flag: '🇦🇺' },
    { text: '🇮🇩 +62  Indonesia', code: '+62', country: 'ID', flag: '🇮🇩' },
    { text: '🇵🇭 +63  Philippines', code: '+63', country: 'PH', flag: '🇵🇭' },
    { text: '🇳🇿 +64  New Zealand', code: '+64', country: 'NZ', flag: '🇳🇿' },
    { text: '🇸🇬 +65  Singapore', code: '+65', country: 'SG', flag: '🇸🇬' },
    { text: '🇹🇭 +66  Thailand', code: '+66', country: 'TH', flag: '🇹🇭' },
    { text: '🇯🇵 +81  Japan', code: '+81', country: 'JP', flag: '🇯🇵' },
    { text: '🇰🇷 +82  South Korea', code: '+82', country: 'KR', flag: '🇰🇷' },
    { text: '🇻🇳 +84  Vietnam', code: '+84', country: 'VN', flag: '🇻🇳' },
    { text: '🇨🇳 +86  China', code: '+86', country: 'CN', flag: '🇨🇳' },
    { text: '🇹🇷 +90  Turkey', code: '+90', country: 'TR', flag: '🇹🇷' },
    { text: '🇮🇳 +91  India', code: '+91', country: 'IN', flag: '🇮🇳' },
    { text: '🇵🇰 +92  Pakistan', code: '+92', country: 'PK', flag: '🇵🇰' },
    { text: '🇦🇫 +93  Afghanistan', code: '+93', country: 'AF', flag: '🇦🇫' },
    { text: '🇱🇰 +94  Sri Lanka', code: '+94', country: 'LK', flag: '🇱🇰' },
    { text: '🇲🇲 +95  Myanmar', code: '+95', country: 'MM', flag: '🇲🇲' },
    { text: '🇮🇷 +98  Iran', code: '+98', country: 'IR', flag: '🇮🇷' },
    { text: '🇲🇦 +212 Morocco', code: '+212', country: 'MA', flag: '🇲🇦' },
    { text: '🇩🇿 +213 Algeria', code: '+213', country: 'DZ', flag: '🇩🇿' },
    { text: '🇹🇳 +216 Tunisia', code: '+216', country: 'TN', flag: '🇹🇳' },
    { text: '🇱🇾 +218 Libya', code: '+218', country: 'LY', flag: '🇱🇾' },
    { text: '🇬🇲 +220 Gambia', code: '+220', country: 'GM', flag: '🇬🇲' },
    { text: '🇸🇳 +221 Senegal', code: '+221', country: 'SN', flag: '🇸🇳' },
    { text: '🇲🇷 +222 Mauritania', code: '+222', country: 'MR', flag: '🇲🇷' },
    { text: '🇲🇱 +223 Mali', code: '+223', country: 'ML', flag: '🇲🇱' },
    { text: '🇬🇳 +224 Guinea', code: '+224', country: 'GN', flag: '🇬🇳' },
    { text: '🇨🇮 +225 Ivory Coast', code: '+225', country: 'CI', flag: '🇨🇮' },
    { text: '🇧🇫 +226 Burkina Faso', code: '+226', country: 'BF', flag: '🇧🇫' },
    { text: '🇳🇪 +227 Niger', code: '+227', country: 'NE', flag: '🇳🇪' },
    { text: '🇹🇬 +228 Togo', code: '+228', country: 'TG', flag: '🇹🇬' },
    { text: '🇧🇯 +229 Benin', code: '+229', country: 'BJ', flag: '🇧🇯' },
    { text: '🇲🇺 +230 Mauritius', code: '+230', country: 'MU', flag: '🇲🇺' },
    { text: '🇱🇷 +231 Liberia', code: '+231', country: 'LR', flag: '🇱🇷' },
    { text: '🇸🇱 +232 Sierra Leone', code: '+232', country: 'SL', flag: '🇸🇱' },
    { text: '🇬🇭 +233 Ghana', code: '+233', country: 'GH', flag: '🇬🇭' },
    { text: '🇳🇬 +234 Nigeria', code: '+234', country: 'NG', flag: '🇳🇬' },
    { text: '🇹🇩 +235 Chad', code: '+235', country: 'TD', flag: '🇹🇩' },
    { text: '🇨🇫 +236 Central African Republic', code: '+236', country: 'CF', flag: '🇨🇫' },
    { text: '🇨🇲 +237 Cameroon', code: '+237', country: 'CM', flag: '🇨🇲' },
    { text: '🇨🇻 +238 Cape Verde', code: '+238', country: 'CV', flag: '🇨🇻' },
    { text: '🇸🇹 +239 Sao Tome and Principe', code: '+239', country: 'ST', flag: '🇸🇹' },
    { text: '🇬🇶 +240 Equatorial Guinea', code: '+240', country: 'GQ', flag: '🇬🇶' },
    { text: '🇬🇦 +241 Gabon', code: '+241', country: 'GA', flag: '🇬🇦' },
    { text: '🇨🇬 +242 Republic of the Congo', code: '+242', country: 'CG', flag: '🇨🇬' },
    { text: '🇨🇩 +243 Democratic Republic of the Congo', code: '+243', country: 'CD', flag: '🇨🇩' },
    { text: '🇦🇴 +244 Angola', code: '+244', country: 'AO', flag: '🇦🇴' },
    { text: '🇬🇼 +245 Guinea-Bissau', code: '+245', country: 'GW', flag: '🇬🇼' },
    { text: '🇮🇴 +246 British Indian Ocean Territory', code: '+246', country: 'IO', flag: '🇮🇴' },
    { text: '🇸🇨 +248 Seychelles', code: '+248', country: 'SC', flag: '🇸🇨' },
    { text: '🇸🇩 +249 Sudan', code: '+249', country: 'SD', flag: '🇸🇩' },
    { text: '🇷🇼 +250 Rwanda', code: '+250', country: 'RW', flag: '🇷🇼' },
    { text: '🇪🇹 +251 Ethiopia', code: '+251', country: 'ET', flag: '🇪🇹' },
    { text: '🇸🇴 +252 Somalia', code: '+252', country: 'SO', flag: '🇸🇴' },
    { text: '🇩🇯 +253 Djibouti', code: '+253', country: 'DJ', flag: '🇩🇯' },
    { text: '🇰🇪 +254 Kenya', code: '+254', country: 'KE', flag: '🇰🇪' },
    { text: '🇹🇿 +255 Tanzania', code: '+255', country: 'TZ', flag: '🇹🇿' },
    { text: '🇺🇬 +256 Uganda', code: '+256', country: 'UG', flag: '🇺🇬' },
    { text: '🇧🇮 +257 Burundi', code: '+257', country: 'BI', flag: '🇧🇮' },
    { text: '🇲🇿 +258 Mozambique', code: '+258', country: 'MZ', flag: '🇲🇿' },
    { text: '🇿🇲 +260 Zambia', code: '+260', country: 'ZM', flag: '🇿🇲' },
    { text: '🇲🇬 +261 Madagascar', code: '+261', country: 'MG', flag: '🇲🇬' },
    { text: '🇷🇪 +262 Reunion', code: '+262', country: 'RE', flag: '🇷🇪' },
    { text: '🇿🇼 +263 Zimbabwe', code: '+263', country: 'ZW', flag: '🇿🇼' },
    { text: '🇳🇦 +264 Namibia', code: '+264', country: 'NA', flag: '🇳🇦' },
    { text: '🇲🇼 +265 Malawi', code: '+265', country: 'MW', flag: '🇲🇼' },
    { text: '🇱🇸 +266 Lesotho', code: '+266', country: 'LS', flag: '🇱🇸' },
    { text: '🇧🇼 +267 Botswana', code: '+267', country: 'BW', flag: '🇧🇼' },
    { text: '🇸🇿 +268 Eswatini', code: '+268', country: 'SZ', flag: '🇸🇿' },
    { text: '🇰🇲 +269 Comoros', code: '+269', country: 'KM', flag: '🇰🇲' },
    { text: '🇸🇭 +290 Saint Helena', code: '+290', country: 'SH', flag: '🇸🇭' },
    { text: '🇪🇷 +291 Eritrea', code: '+291', country: 'ER', flag: '🇪🇷' },
    { text: '🇦🇼 +297 Aruba', code: '+297', country: 'AW', flag: '🇦🇼' },
    { text: '🇫🇴 +298 Faroe Islands', code: '+298', country: 'FO', flag: '🇫🇴' },
    { text: '🇬🇱 +299 Greenland', code: '+299', country: 'GL', flag: '🇬🇱' },
    { text: '🇬🇮 +350 Gibraltar', code: '+350', country: 'GI', flag: '🇬🇮' },
    { text: '🇵🇹 +351 Portugal', code: '+351', country: 'PT', flag: '🇵🇹' },
    { text: '🇱🇺 +352 Luxembourg', code: '+352', country: 'LU', flag: '🇱🇺' },
    { text: '🇮🇪 +353 Ireland', code: '+353', country: 'IE', flag: '🇮🇪' },
    { text: '🇮🇸 +354 Iceland', code: '+354', country: 'IS', flag: '🇮🇸' },
    { text: '🇦🇱 +355 Albania', code: '+355', country: 'AL', flag: '🇦🇱' },
    { text: '🇲🇹 +356 Malta', code: '+356', country: 'MT', flag: '🇲🇹' },
    { text: '🇨🇾 +357 Cyprus', code: '+357', country: 'CY', flag: '🇨🇾' },
    { text: '🇫🇮 +358 Finland', code: '+358', country: 'FI', flag: '🇫🇮' },
    { text: '🇧🇬 +359 Bulgaria', code: '+359', country: 'BG', flag: '🇧🇬' },
    { text: '🇱🇹 +370 Lithuania', code: '+370', country: 'LT', flag: '🇱🇹' },
    { text: '🇱🇻 +371 Latvia', code: '+371', country: 'LV', flag: '🇱🇻' },
    { text: '🇪🇪 +372 Estonia', code: '+372', country: 'EE', flag: '🇪🇪' },
    { text: '🇲🇩 +373 Moldova', code: '+373', country: 'MD', flag: '🇲🇩' },
    { text: '🇦🇲 +374 Armenia', code: '+374', country: 'AM', flag: '🇦🇲' },
    { text: '🇧🇾 +375 Belarus', code: '+375', country: 'BY', flag: '🇧🇾' },
    { text: '🇦🇩 +376 Andorra', code: '+376', country: 'AD', flag: '🇦🇩' },
    { text: '🇲🇨 +377 Monaco', code: '+377', country: 'MC', flag: '🇲🇨' },
    { text: '🇸🇲 +378 San Marino', code: '+378', country: 'SM', flag: '🇸🇲' },
    { text: '🇺🇦 +380 Ukraine', code: '+380', country: 'UA', flag: '🇺🇦' },
    { text: '🇷🇸 +381 Serbia', code: '+381', country: 'RS', flag: '🇷🇸' },
    { text: '🇲🇪 +382 Montenegro', code: '+382', country: 'ME', flag: '🇲🇪' },
    { text: '🇭🇷 +385 Croatia', code: '+385', country: 'HR', flag: '🇭🇷' },
    { text: '🇸🇮 +386 Slovenia', code: '+386', country: 'SI', flag: '🇸🇮' },
    { text: '🇧🇦 +387 Bosnia and Herzegovina', code: '+387', country: 'BA', flag: '🇧🇦' },
    { text: '🇲🇰 +389 North Macedonia', code: '+389', country: 'MK', flag: '🇲🇰' },
    { text: '🇨🇿 +420 Czech Republic', code: '+420', country: 'CZ', flag: '🇨🇿' },
    { text: '🇸🇰 +421 Slovakia', code: '+421', country: 'SK', flag: '🇸🇰' },
    { text: '🇱🇮 +423 Liechtenstein', code: '+423', country: 'LI', flag: '🇱🇮' },
    { text: '🇫🇰 +500 Falkland Islands', code: '+500', country: 'FK', flag: '🇫🇰' },
    { text: '🇧🇿 +501 Belize', code: '+501', country: 'BZ', flag: '🇧🇿' },
    { text: '🇬🇹 +502 Guatemala', code: '+502', country: 'GT', flag: '🇬🇹' },
    { text: '🇸🇻 +503 El Salvador', code: '+503', country: 'SV', flag: '🇸🇻' },
    { text: '🇭🇳 +504 Honduras', code: '+504', country: 'HN', flag: '🇭🇳' },
    { text: '🇳🇮 +505 Nicaragua', code: '+505', country: 'NI', flag: '🇳🇮' },
    { text: '🇨🇷 +506 Costa Rica', code: '+506', country: 'CR', flag: '🇨🇷' },
    { text: '🇵🇦 +507 Panama', code: '+507', country: 'PA', flag: '🇵🇦' },
    { text: '🇵🇲 +508 Saint Pierre and Miquelon', code: '+508', country: 'PM', flag: '🇵🇲' },
    { text: '🇭🇹 +509 Haiti', code: '+509', country: 'HT', flag: '🇭🇹' },
    { text: '🇬🇵 +590 Guadeloupe', code: '+590', country: 'GP', flag: '🇬🇵' },
    { text: '🇧🇴 +591 Bolivia', code: '+591', country: 'BO', flag: '🇧🇴' },
    { text: '🇬🇾 +592 Guyana', code: '+592', country: 'GY', flag: '🇬🇾' },
    { text: '🇪🇨 +593 Ecuador', code: '+593', country: 'EC', flag: '🇪🇨' },
    { text: '🇬🇫 +594 French Guiana', code: '+594', country: 'GF', flag: '🇬🇫' },
    { text: '🇵🇾 +595 Paraguay', code: '+595', country: 'PY', flag: '🇵🇾' },
    { text: '🇲🇶 +596 Martinique', code: '+596', country: 'MQ', flag: '🇲🇶' },
    { text: '🇸🇷 +597 Suriname', code: '+597', country: 'SR', flag: '🇸🇷' },
    { text: '🇺🇾 +598 Uruguay', code: '+598', country: 'UY', flag: '🇺🇾' },
    { text: '🇨🇼 +599 Curaçao', code: '+599', country: 'CW', flag: '🇨🇼' },
    { text: '🇹🇱 +670 Timor-Leste', code: '+670', country: 'TL', flag: '🇹🇱' },
    { text: '🇦🇶 +672 Antarctica', code: '+672', country: 'AQ', flag: '🇦🇶' },
    { text: '🇧🇳 +673 Brunei', code: '+673', country: 'BN', flag: '🇧🇳' },
    { text: '🇳🇷 +674 Nauru', code: '+674', country: 'NR', flag: '🇳🇷' },
    { text: '🇵🇬 +675 Papua New Guinea', code: '+675', country: 'PG', flag: '🇵🇬' },
    { text: '🇹🇴 +676 Tonga', code: '+676', country: 'TO', flag: '🇹🇴' },
    { text: '🇸🇧 +677 Solomon Islands', code: '+677', country: 'SB', flag: '🇸🇧' },
    { text: '🇻🇺 +678 Vanuatu', code: '+678', country: 'VU', flag: '🇻🇺' },
    { text: '🇫🇯 +679 Fiji', code: '+679', country: 'FJ', flag: '🇫🇯' },
    { text: '🇵🇼 +680 Palau', code: '+680', country: 'PW', flag: '🇵🇼' },
    { text: '🇼🇫 +681 Wallis and Futuna', code: '+681', country: 'WF', flag: '🇼🇫' },
    { text: '🇨🇰 +682 Cook Islands', code: '+682', country: 'CK', flag: '🇨🇰' },
    { text: '🇳🇺 +683 Niue', code: '+683', country: 'NU', flag: '🇳🇺' },
    { text: '🇼🇸 +685 Samoa', code: '+685', country: 'WS', flag: '🇼🇸' },
    { text: '🇰🇮 +686 Kiribati', code: '+686', country: 'KI', flag: '🇰🇮' },
    { text: '🇳🇨 +687 New Caledonia', code: '+687', country: 'NC', flag: '🇳🇨' },
    { text: '🇹🇻 +688 Tuvalu', code: '+688', country: 'TV', flag: '🇹🇻' },
    { text: '🇵🇫 +689 French Polynesia', code: '+689', country: 'PF', flag: '🇵🇫' },
    { text: '🇹🇰 +690 Tokelau', code: '+690', country: 'TK', flag: '🇹🇰' },
    { text: '🇫🇲 +691 Federated States of Micronesia', code: '+691', country: 'FM', flag: '🇫🇲' },
    { text: '🇲🇭 +692 Marshall Islands', code: '+692', country: 'MH', flag: '🇲🇭' },
    { text: '🇰🇵 +850 North Korea', code: '+850', country: 'KP', flag: '🇰🇵' },
    { text: '🇭🇰 +852 Hong Kong', code: '+852', country: 'HK', flag: '🇭🇰' },
    { text: '🇲🇴 +853 Macau', code: '+853', country: 'MO', flag: '🇲🇴' },
    { text: '🇰🇭 +855 Cambodia', code: '+855', country: 'KH', flag: '🇰🇭' },
    { text: '🇱🇦 +856 Laos', code: '+856', country: 'LA', flag: '🇱🇦' },
    { text: '🇧🇩 +880 Bangladesh', code: '+880', country: 'BD', flag: '🇧🇩' },
    { text: '🇹🇼 +886 Taiwan', code: '+886', country: 'TW', flag: '🇹🇼' },
    { text: '🇲🇻 +960 Maldives', code: '+960', country: 'MV', flag: '🇲🇻' },
    { text: '🇱🇧 +961 Lebanon', code: '+961', country: 'LB', flag: '🇱🇧' },
    { text: '🇯🇴 +962 Jordan', code: '+962', country: 'JO', flag: '🇯🇴' },
    { text: '🇸🇾 +963 Syria', code: '+963', country: 'SY', flag: '🇸🇾' },
    { text: '🇮🇶 +964 Iraq', code: '+964', country: 'IQ', flag: '🇮🇶' },
    { text: '🇰🇼 +965 Kuwait', code: '+965', country: 'KW', flag: '🇰🇼' },
    { text: '🇸🇦 +966 Saudi Arabia', code: '+966', country: 'SA', flag: '🇸🇦' },
    { text: '🇾🇪 +967 Yemen', code: '+967', country: 'YE', flag: '🇾🇪' },
    { text: '🇴🇲 +968 Oman', code: '+968', country: 'OM', flag: '🇴🇲' },
    { text: '🇵🇸 +970 Palestine', code: '+970', country: 'PS', flag: '🇵🇸' },
    { text: '🇦🇪 +971 United Arab Emirates', code: '+971', country: 'AE', flag: '🇦🇪' },
    { text: '🇮🇱 +972 Israel', code: '+972', country: 'IL', flag: '🇮🇱' },
    { text: '🇧🇭 +973 Bahrain', code: '+973', country: 'BH', flag: '🇧🇭' },
    { text: '🇶🇦 +974 Qatar', code: '+974', country: 'QA', flag: '🇶🇦' },
    { text: '🇧🇹 +975 Bhutan', code: '+975', country: 'BT', flag: '🇧🇹' },
    { text: '🇲🇳 +976 Mongolia', code: '+976', country: 'MN', flag: '🇲🇳' },
    { text: '🇳🇵 +977 Nepal', code: '+977', country: 'NP', flag: '🇳🇵' },
    { text: '🇹🇯 +992 Tajikistan', code: '+992', country: 'TJ', flag: '🇹🇯' },
    { text: '🇹🇲 +993 Turkmenistan', code: '+993', country: 'TM', flag: '🇹🇲' },
    { text: '🇦🇿 +994 Azerbaijan', code: '+994', country: 'AZ', flag: '🇦🇿' },
    { text: '🇬🇪 +995 Georgia', code: '+995', country: 'GE', flag: '🇬🇪' },
    { text: '🇰🇬 +996 Kyrgyzstan', code: '+996', country: 'KG', flag: '🇰🇬' },
    { text: '🇺🇿 +998 Uzbekistan', code: '+998', country: 'UZ', flag: '🇺🇿' },
  ]

  constructor() { }

  getPhoneNumbers() {
    return this.phoneNumbers
  }

  // async signUp(phone: string, recaptchaVerifier: RecaptchaVerifier): Promise<ConfirmationResult> {
  //   return signInWithPhoneNumber(this.auth, phone, recaptchaVerifier)
  // }
  
}
